version: "3"

services:
  api:
    build: ./api
    container_name: api
    restart: always
    ports:
      - "5000"

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"