FROM python:3.9

ENV API_DIR /app/api

WORKDIR ${API_DIR}

COPY requirements.txt .
RUN pip install --upgrade pip wheel setuptools \
    && pip install -r requirements.txt

COPY . .
CMD ["uwsgi", "uwsgi.ini"]